# Windows Firewall Rules
# Generated by ZeroTrust Inspector
# Policy: {{ policy_name }}

# Remove old rules
Get-NetFirewallRule | Where-Object {$_.DisplayName -like "ZTI_*"} | Remove-NetFirewallRule

# Create new rules
{% for rule in rules %}
$ruleName = "ZTI_{{ rule.source_ip }}_to_{{ rule.dest_ip }}"
New-NetFirewallRule `
    -DisplayName $ruleName `
    -Description "{{ rule.description }}" `
    -Enabled True `
    -Direction Outbound `
    -Protocol {{ rule.protocol }} `
    {% if rule.ports %}
    -RemotePort {{ rule.ports|join(",") }} `
    {% endif %}
    -RemoteAddress {{ rule.dest_ip }} `
    -LocalAddress {{ rule.source_ip }} `
    -Action {{ rule.action|title }} `
    -EdgeTraversalPolicy Block
    {% if rule.action == 'allow' %}
    -Profile Any
    {% endif %}

Write-Host "Created rule: $ruleName"
{% endfor %}

Write-Host "Windows Firewall rules applied successfully!"